services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dataB
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5433:5432' #maps host port 5433 to container port 5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local

